---
title: "correlation analysis of the small leucine rich proteoglycans"
author: "BS"
date: "22/08/2022"
output: github_document
---

### load libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(GGally)
library(cowplot)
```


### load the data
```{r}
data <- read.delim("SLRP.txt", header = T, sep = "\t", row.names = "Animal")
```


### plot and save 
```{r message=FALSE, warning=FALSE}
#https://stackoverflow.com/questions/30858337/how-to-customize-lines-in-ggpairs-ggally
lowerFn <- function(data, mapping, method = "lm", ...) {
    p <- ggplot(data = data, mapping = mapping) +
    geom_point(colour = "navy", size = 1.5)+
    geom_smooth(method = method, size = 0.5, color = "black", ...)
  p
}

scatter <- ggpairs(
  data[, 1:6], lower = list(continuous = wrap(lowerFn, method = "lm")),
  diag = "blank",
  upper = list(continuous = wrap("cor", method = "spearman", size = 3, colour = "black"))
    
)+
  theme_bw()+
  theme(panel.border = element_rect(size = 1, colour = "black"),
        panel.grid =element_blank())+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, colour = "black"),
        axis.text.y = element_text(colour = "black"))+
  theme(strip.text = element_text(size = 9, colour = "black"),
        axis.ticks = element_line(colour = "black"))+
  theme(strip.background = element_blank())+
  theme(axis.text = element_text(size = 9))

plot_grid(
   ggmatrix_gtable(scatter),
   nrow = 1)
ggsave("slrpgcorrplot.svg", width = 5, height = 5)
```


